### ISSUE TITLE
Violentmonkey Support

### ISSUE THREAD

**Issue by jlneder** [Tomaszal/nix-manual-enhancements#1]
I tried with Violentmonkey and it doesn't work at all.
I then installed tampermonkey and could see that is gorgeous.
If you can add support for Violentmonkey it would be awesome. I don't like to have two extensions installed for the same functionality.

**Comment by Tomaszal** [comment]
I tried installing it on Violentmonkey just now and it seems to be working both on Firefox and Chromium. Could you let me know the version of your browser and extension? Also, could you see if there are any errors in the dev tools console?

**Comment by jlneder** [comment]
I'm sorry. I really don't know what happen.
I disabled tampermoney and tried the script from violentmonkey again and now is working perfectly. But I didn't change anything!!
I really don't know what could have happened.
My apologies.

**Comment by Tomaszal** [comment]
No worries, I'm glad that it works. It's probably some sort of an edge-case that you stumbled upon, but without logs it's hard to tell. I'll close this issue for now, but if it happens again to you or someone else, feel free to update this issue with some more info and I'll take a look at it.
